languageCode = "zh-cn"
languageName = "简体中文"
weight = 4
title = "OHULAB"

[params]
  displayName = "简体中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/logo.png"
  description = "天人合一科学实验室"

[params.author]
  name = "天人合一科学实验室"
  image = "img/logo.png"
  headline = "用科学的方式检验万物一体的生命与宇宙本质。"
  bio = "简介。。。"
  links = [
    { x-twitter = "https://twitter.com/burufugu" },
    { github = "https://github.com/nunocoracao/blowfish" },
  ]