disabled = false

#文字编码
languageCode = "zh-cn"  

#多语言显示名称
languageName = "简体中文"  
weight = 2
title = "OHULAB"

[params]
  displayName = "简体中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2 January 2006"

  # logo = "logo1.png" #夜晚模式首页左上角LOGO
  # secondaryLogo = "logo2.png" #白天模式首页左上角LOGO
  
  description = "用科学的方式检验万物一体的存在本质"

[params.author]
  image = "logo3.png" #首页中心LOGO
  name = "OHULAB" #首页中间LOGO下大字名称
  email = "ohulab.org@gmail.com"
  # headline = "天人合一科学实验室"   #首页标语
  bio = "用科学的方式检验万物一体的存在本质"   #文章页作者图标下说明标语
  links = [
    { x-twitter = "https://x.com/BlueyASI_org" },
    { bluesky = "#" },
    { facebook = "#" },
    { instagram = "#" },
    { telegram = "#" },
    { github = "#" },
  ]  #文章页作者LOGO下社交媒体图标连接
