languageCode = "en"
languageName = "English"
weight = 1
title = "OHULAB"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logo.png"
  description = "A powerful, lightweight theme for Hugo."

[params.author]
  name = "Oneness of Human and Universe Laboratory"
  email = "ohulab.org@gmail.com"
  image = "img/logo.png"
  headline = "Oneness of Human and Universe Laboratory"
  bio = "Oneness of Human and Universe Laboratory."
  links = [
    { x-twitter = "https://twitter.com/burufugu" },
    { github = "https://github.com/nunocoracao/blowfish" },
  ]