[[main]]
name = "关于"
pageRef = "#"
weight = 1

[[main]]
name = "愿景"
pageRef = "#"
weight = 2

[[main]]
name = "动机"
pageRef = "#"
weight = 3

[[main]]
name = "项目"
pageRef = "#"
weight = 4

[[main]]
name = "博客"
pageRef = "#"
weight = 5

[[main]]
name = "会员"
pageRef = "#"
weight = 6

[[main]]
name = "联系"
pageRef = "#"
weight = 7

[[main]]
pre = "github"
url = "#"
weight = 8


[[footer]]
  name = "标签导航"
  pageRef = "Tags"
  weight = 21

[[footer]]
  name = "问答集锦"
  pageRef = "FAQs"
  weight = 22

[[footer]]
name = "隐私政策"
pageRef = "#"
weight = 23

[[footer]]
name = "网站架构"
pageRef = "WebsiteStack"
weight = 24







