[[main]]
name = "About"
pageRef = "#"
weight = 1

[[main]]
name = "Vision"
pageRef = "#"
weight = 2

[[main]]
name = "Motivation"
pageRef = "#"
weight = 3

[[main]]
name = "Projects"
pageRef = "#"
weight = 4

[[main]]
name = "Blog"
pageRef = "#"
weight = 5

[[main]]
name = "Premium"
pageRef = "#"
weight = 6

[[main]]
name = "Contact"
pageRef = "#"
weight = 7


[[main]]
pre = "github"
url = "#"
weight = 8


[[footer]]
  name = "Tags"
  pageRef = "Tags"
  weight = 21

[[footer]]
  name = "FAQs"
  pageRef = "FAQs"
  weight = 22

[[footer]]
  name = "Privacy Policy"
  pageRef = "#"
  weight = 23

[[footer]]
  name = "Website Stack"
  pageRef = "WebsiteStack"
  weight = 24








